main_app/urls.py
from django.urls import path 
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('plants/', views.plants_index, name='index'),
    path('plants/<int:plant_id>/', views.plants_detail, name='detail'),
    path('plants/create/', views.PlantCreate.as_view(), name='plants_create'),
    path('plants/<int:pk>/update', views.PlantUpdate.as_view(), name='plants_update'), 
    path('plants/<int:pk>/delete', views.PlantDelete.as_view(), name='plants_delete'), 
    path('plants/<int:plant_id>/add_watering/', views.add_watering, name='add_watering'),
    path('accounts/signup/', views.signup, name='signup'),
]

plants/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

TYPES = (
    ('W', 'Watering'), 
    ('F', 'Fertilization'), 
    ('R', 'Repotting')
)

# Create your models here.
class Plant(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    type = models.CharField(max_length=50)
    difficultyLevel = models.IntegerField()
    waterFrequency = models.CharField(max_length=100)
    fertilization = models.CharField(max_length=100)
    repotting = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'plant_id':self.id})

class Watering(models.Model):
    date = models.DateField()
    type = models.CharField(
        max_length=1,
        choices=TYPES, 
        default=TYPES[0][0]
    )

    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_type_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Watering

class WateringForm(ModelForm):
  class Meta:
    model = Watering
    fields = ['date', 'type']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Plant
from .forms import WateringForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def plants_index(request):
    plants = Plant.objects.filter(user=request.user)
    return render(request, 'plants/index.html', {'plants':plants})

@login_required
def plants_detail(request, plant_id):
    plant = Plant.objects.get(id=plant_id)
    watering_form = WateringForm()
    return render(request, 'plants/detail.html', {'plant':plant, 'watering_form': watering_form})

@login_required
def add_watering(request, plant_id):
    form = WateringForm(request.POST)
    if form.is_valid():
        new_watering = form.save(commit=False)
        new_watering.plant_id = plant_id
        new_watering.save()
    return redirect('detail', plant_id=plant_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

class PlantCreate(LoginRequiredMixin, CreateView):
    model = Plant
    fields = ['name', 'description', 'type', 'difficultyLevel', 'waterFrequency', 'fertilization', 'repotting']
    success_url = '/plants/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class PlantUpdate(LoginRequiredMixin, UpdateView):
    model = Plant
    fields = '__all__'

class PlantDelete(LoginRequiredMixin, DeleteView):
    model = Plant
    success_url = '/plants/'

main_app/templates/about.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Blossom</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link
      href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Sansita+Swashed:wght@500&display=swap"
      rel="stylesheet"
    />
  </head>
  <body class="about">
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper blue-grey darken-4">
          <ul>
            <li>
              <a href="/" class="left-brand-logo">Blossom &#127797;</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'plants_create' %}">Add a Plant</a></li>
            <li><a href="{% url 'index' %}">View My Plants</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="about-p">
      <div class="row">
        <div class="col s6">
          <h1 class="about-intro">About Blossom</h1>
          <hr />
          <p>Do you find it hard to constantly keep track of what plants you have, when to water them, not to mention fertilize or repot them? Here's where <b>Blossom</b> comes in handy. How this works...</p>
        <div class="p-smaller">
          <p>&#127797 Add your plants in the Add a Plant tab above</p>
          <p>&#128395 Be sure to give a detailed description about your plants as we haven't implemented photo functions (just yet ...)</p>
          <p>&#128198 Update everytime you water, fertilize, or repot your plants</p>
          <p>&#127793 Visit us when it's time to water your plants and repeat to see your plants flourish!</p>
        </div>
        </div>
      </div>
    </main>
    <footer class="page-footer transparent">
      <div class="center">All Rights Reserved, &copy; 2022 Blossom</div>
    </footer>
  </body>
</html>

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Blossom</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link
      href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Sansita+Swashed:wght@500&display=swap"
      rel="stylesheet"
    />
  </head>
  <body class="base-background">
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper blue-grey darken-4">
          <ul>
            <li>
              <a href="/" class="left-brand-logo">Blossom &#127797;</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'plants_create' %}">Add a Plant</a></li>
            <li><a href="{% url 'index' %}">View My Plants</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">
        {% block content %} {% endblock %}
    </main>
  </body>
</html>

main_app/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Blossom</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Sansita+Swashed:wght@500&display=swap" rel="stylesheet">
  </head>
  <body class="home">
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper blue-grey darken-4">
          <ul>
            <li>
              <a href="/" class="left-brand-logo">Blossom &#127797;</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'plants_create' %}">Add a Plant</a></li>
            <li><a href="{% url 'index' %}">View My Plants</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
        <main class="home-container">
          <h3 class="home-intro">Not dead yet<br />succa</h3>
          <h5 class="home-p">Say hello to the plant app that helps you keep <br />track of waterings, fertilization, and repotting times <br />to keep those plants healthy and happy.</h5>
        </main>

    <footer class="page-footer transparent">
      <div class="center">All Rights Reserved, &copy; 2022 Blossom</div>
    </footer>
  </body>
</html>

main_app/templates/main_app/plant_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1 style="font-family: Georgia, 'Times New Roman', Times, serif;">Delete Plant</h1>

<h4>
  Are you sure you want to delete
  <span class="red-text"><b>{{ object.name }}</b></span>?
</h4>
<br />
<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn red darken-4" />
  <a href="{% url 'detail' plant.id %}"> Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/plant_form.html
{% extends 'base.html' %} {% block content %}
{% if object %}
<h1 style="font-family: Georgia, 'Times New Roman', Times, serif;">Edit <span class="green-text">{{object.name}}</span></h1>
{% else %}
<h1 style="text-align: center; font-family: Georgia, 'Times New Roman', Times, serif;">Add Plant</h1>
{% endif %}

<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <br />
  <input type="submit" value="Submit!" class="btn green darken-1" />
</form>
<br />
{% endblock %}

main_app/templates/plants/detail.html
{% extends 'base.html' %} {% block content %}

<h1 style="margin-left: 60px; font-family: Georgia, 'Times New Roman', Times, serif;">Plant Details</h1>

<div class="row">
  <div class="col s6">
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ plant.name }}</span>
    <p>Description: {{ plant.description }}</p>
    <p>Type: {{ plant.type }}</p>
    <p>Difficulty Level: {{ plant.difficultyLevel }}/10</p>
    <p>Water Frequency: {{ plant.waterFrequency }}</p>
    <p>Fertilization Frequency: {{ plant.fertilization }}</p>
    <p>Repotting Frequency: {{ plant.repotting }}</p>
  </div>
  <div class="card-action green lighten-5">
    <a href="{% url 'plants_update' plant.id %}" style="color: rgb(13, 113, 58);">Edit</a>
    <a href="{% url 'plants_delete' plant.id %}" style="color: rgb(13, 113, 58);">Delete</a>
  </div>
</div>
</div>
<div class="col s6">
  <form action="{% url 'add_watering' plant.id %}"method="post">
    {% csrf_token %} {{ watering_form.as_p }}
    <input type="submit" class="btn green" value="Add Type" />
  </form>
  <table class="striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Type</th>
      </tr>
    </thead>
    <tbody>
      {% for watering in plant.watering_set.all %}
      <tr>
        <td>{{watering.date}}</td>
        <td>{{watering.get_type_display}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>

<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  var selectEl = document.getElementById('id_type');
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/plants/index.html
{% extends 'base.html' %} {% block content %}

<h1 style="text-align: center; font-family: Georgia, 'Times New Roman', Times, serif;">Plant List</h1>
<p style="text-align: center;">~ Click on a card to view more details! ~</p>

{% for plant in plants %}
<div class="card">
<a href="{% url 'detail' plant.id %}">
  <div style="color: rgb(23, 119, 52);" class="card-content">
    <span class="card-title">{{ plant.name }}</span>
    <p>Description: {{ plant.description }}</p>
  </div>
</a>
</div>
{% endfor %} {% endblock %}